### ISSUE TITLE
Cloudflare Zero Trust session revocation handling

### ISSUE THREAD

**Issue by lutzky** [silverbulletmd/silverbullet#1091]
Cloudflare Zero Trust, as explained in [this guide](https://community.silverbullet.md/t/cloudflare-and-portainer/31), can be used to configure external/better/safer/more-convenient authentication. However, there's an issue with session expiration: Whenever a session expires (this can be forced as explained in [cloudflare zero trust's session management docs](https://developers.cloudflare.com/cloudflare-one/identity/users/session-management/), the app UI will show as "offline" (red header), and the JS console will show the following message:

> Access to fetch at 'https://lutzky.cloudflareaccess.com/cdn-cgi/access/login/MY_SILVERBULLET_DOMAIN_REDACTED?kid=LONG_REDACTED_STRING&redirect_url=%2FProjects%2FSilverBullet.md&meta=LONG_REDACTED_STRING' (redirected from 'https://MY_SILVERBULLET_DOMAIN_REDACTED/Projects/SilverBullet.md') from origin 'https://MY_SILVERBULLET_DOMAIN_REDACTED' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This is true for version 0.9.4. It is possible that https://github.com/silverbulletmd/silverbullet/commit/f7fe7cadbcc2b36bbc2049199fcb8cc46e056283 changes this, but I'm opening this issue anyway to make sure it doesn't get missed while working on #1028. What we should see is a full-fat redirect.

I guess this is a known issue for the general case, e.g. [this 2019 report about the same issue for a different app](https://community.cloudflare.com/t/pwa-application-behind-cloudflare-access/122050), but I figure that the app can be customized to overcome this.

Workarounds:
* On machines with keyboards running Chrome, Ctrl-Shift-R issues enough of a reload to allow re-authentication.
* On machines without keyboards (e.g. Android phones), there does not appear to be a way to "reload that hard" - and only a "delete site data" bit works, thereby causing a full re-sync (and losing any data you wrote while offline).

**Comment by zefhemel** [comment]
Yes I think this is the same issues as #1028 but here it's blocked due to CORS. What I need to figure out how to detect this is happening when I perform the fetch, if I can (i'd have to create a setup that replicates this) detect this I can attempt the unregister service worker and reload approach.

**Comment by lutzky** [comment]
That makes sense. I'm thinking something along the lines of accessing a test instance through a proxy that will usually just forward traffic to real-silverbullet, but on-command will start redirecting to https://example.com/ (that should be "distant enough" CORS-wise); indeed, detecting that that happened and doing an unregister-and-reload should do the trick.

**Comment by lutzky** [comment]
Indeed, this reproduces the condition:

1. Start a local server (default port 3000), set it to sync mode
2. Open browser, write some files
3. Kill the server
4. Run the following:

```bash
while true; do echo -ne "HTTP/1.1 301 Moved Permanently\r\nLocation: https://example.com\r\n\r\n" | nc -N -l -p 3000; done
```

Indeed, this generates the following error:

> Access to fetch at 'https://example.com/' (redirected from 'http://localhost:3000/index.md') from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Desired behavior - the browser should redirect to https://example.com.

**Comment by zefhemel** [comment]
I pushed something to main. Could you try if this solves it for you? It's in the edge build.

**Comment by lutzky** [comment]
There's definitely some weirdness going on. I need to improve my test setup and take a better look at this tomorrow, but one thing that I can already clearly identify is that it re-re-redirect to `/.auth` multiple times (I also use `SB_AUTH`), and that it overwrites my `SETTINGS` with its own version. I probably shouldn't test on the prod version of my space :thinking:.

**Comment by lutzky** [comment]
Also - what is the intended upgrade mechanism? That is, I think I had to "delete all site data" for a new version of the upstream to load... but then again maybe I didn't. What's the intended UX, and how does one check?

**Comment by zefhemel** [comment]
Why would you use two levels of auth? I'd disable SB_USER if you use CF for authentication. 

Upgrading on the server depends on if you use docker or Deno. On the client simply reloading the page 2-3x to be safe should be sufficient, no cleaning of any data.

**Comment by lutzky** [comment]
The reason I have two levels of auth is that I want to still require authentication within my home network (e.g. what if my ISP goes down, I want to investigate, and I'd like to use silverbullet to take notes for that). If this is a problem, I could work around it by having a no-`SB_USER` instance exposed only to localhost (and therefore cloudflare), and expose a separate instance during emergencies. Would be nice to explicitly say "this isn't supported" in the docs.

For now, I'm testing without `SB_USER` - so far so good, I'm setting a shorter auto-expiration to see what happens (explicit expiration is somewhat more violent).

Upgrading the server I understand (I use docker), as it's clearly "new version means restart the server binary". What I mean is, on the client, how do I know if I'm indeed using an up-to-date client and not just a cached version of the previous one? Is it `Help: Version`? Maybe we can add a commit ID to that to help debug?

**Comment by lutzky** [comment]
Hmm, now it does seem to work with `SB_USER` as well. Tests I ran include:

- Reducing cloudflare session expiration timeout to 15 minutes and waiting it out
- Changing `SB_USER` and restarting the server

In both cases it seems to be doing the right thing.

I'll now try with a hard re-auth (cloudflare's "revoke sessions" button), which was giving me some trouble before, but I know it refuses to re-auth the user for at least a few minutes.

**Comment by lutzky** [comment]
And, yeah, "revoke sessions" re-authenticated correctly as well. I think some of my synthetic testing with "redirect to example.com" was causing some unrealistic problem with the CORS headers and such, but this seems to work fine!

**Comment by zefhemel** [comment]
Ok happy to hear it. Finally 😆

**Comment by lutzky** [comment]
I'm guessing this is fixed by a combination of https://github.com/silverbulletmd/silverbullet/commit/cb88eae8858b46dcdb4d94776a123a9636e1a872 and https://github.com/silverbulletmd/silverbullet/commit/4eae0c975b7ea75ecbfc967f17d0d6e9bd7679ed. Any more tests you'd like me to run, or do we close this?

**Comment by zefhemel** [comment]
I'll close it. We can always reopen when more issues appear. I hope not, because this has been quite a pain and I'm running into hard browser limits.

**Comment by saytosid** [comment]
This seems to still happen. Getting this error when cloudflare session expires. 

`Could not process config and no cached copy, please connect to the Internet `

This is on ios safari, theres no way to hard refresh to force reauth with CF

**Comment by lutzky** [comment]
Yeah, this has recently-ish broken for me as well.

Current behavior I'm seeing is that, after the session was revoked:

1. I get an alert "Could not process config and no cached copy, please connect to the Internet"
2. ServiceWorker attempts to fetch `/.config`, gets a 302 redirect from cloudflare towards something like `https://your_username_here.cloudflareaccess.com/cdn-cgi/access/login/your.cloudflare.domain.or.something.com/?kid=[.....]&redirect_url=%2F.config`.
3. The whole process kinda bails there
4. Several hours later, this magically resolves itself?

I think we have some nondeterministic behavior here, as I've purposely set my cloudflare-zero-trust sessions to time out after 15 minutes in order to debug this, and it's taking multiple hours to reproduce.

I think this might have been reintroduced in dc2987a3f9a9541233afc2eac8018d547a13f751

Specifically, it commented out line 74, which I think was the workaround for this specific issue.

https://github.com/silverbulletmd/silverbullet/blob/dc2987a3f9a9541233afc2eac8018d547a13f751/lib/spaces/http_space_primitives.ts#L66-L79

However, `authErrorCallback` seems to be a callback to this:

https://github.com/silverbulletmd/silverbullet/blob/ca76e880d7027fd06d8967be06d75654691c1f7d/client/client.ts#L301-L312

...which should perform the reload behavior as expected. I'll keep digging at this, but any pointers from @zefhemel would be super helpful.

**Comment by lutzky** [comment]
OK, digging further into this, apparently the changed behavior is that dc2987a3f9a9541233afc2eac8018d547a13f751 made this change in `spaces/http_space_primitives.ts`:

```diff
@@ -40,19 +42,21 @@ export class HttpSpacePrimitives implements SpacePrimitives {
       options.redirect = "manual";
       const result = await fetch(url, options);
       if (result.status === 503) {
-        throw new Error("Offline");
+        throw offlineError;
       }
       const redirectHeader = result.headers.get("location");

       if (result.type === "opaqueredirect" && !redirectHeader) {
+        console.log("Result", result, "for", url, JSON.stringify(options));
         // This is a scenario where the server sent a redirect, but this redirect is not visible to the client, likely due to CORS
         // The best we can do is to reload the page and hope that the server will redirect us to the correct location
-        alert(
+        this.authErrorCallback(
           "You are not authenticated, reloading to reauthenticate",
+          "reload",
         );
-        console.log("Unregistering service workers", redirectHeader);
-        await unregisterServiceWorkers();
-        location.reload();
+        // console.log("Unregistering service workers", redirectHeader);
+        // await unregisterServiceWorkers();
+        // location.reload();
         // Let's throw to avoid any further processing
         throw Error("Not authenticated");
       }
```

Specifically, we're skipping `unregisterServiceWorkers`, and replacing that with a call to `this.authErrorCallback`. This, in turn, is in `web/service_worker.ts` (anonymously), as the third parameter to the constructor here:

```typescript
      const remote = new HttpSpacePrimitives(
        basePathName + fsEndpoint,
        spaceFolderPath,
        (message, actionOrRedirectHeader) => {
          // And auth error occured
          console.error(
            "[service proxy error]",
            message,
            actionOrRedirectHeader,
          );
          broadcastMessage({
            type: "auth-error",
            message,
            actionOrRedirectHeader,
          });
        },
      );
```

In turn, the handler for the `auth-error` broadcast is in `web/client.ts`, and does this:

```typescript
      case "auth-error": {
        alert(message.message);
        if (message.actionOrRedirectHeader) {
          location.href = message.actionOrRedirectHeader;
        } else {
          location.reload();
        }
```

There's two issues here:
1. Some questionable stringly-typed parameter (if I'm reading this correctly, it's redirecting to... `"redirect"`?)
2. We're not unregistering the service worker anymore

Critically, reloading the page does not work around the issue, but **Ctrl-Reloading** it does! (unfortunately not possible on a phone, and the old `location.reload(true)` syntax doesn't work nowadays).

This patch seems to help, but I seem to be getting into a redirect loop, so I'll investigate some more before making a PR out of this:

```diff
$ git diff client/client.ts
diff --git a/client/client.ts b/client/client.ts
index b08ef566..fe230097 100644
--- a/client/client.ts
+++ b/client/client.ts
@@ -80,6 +80,7 @@ import type { KvPrimitives } from "./data/kv_primitives.ts";
 import { deriveDbName } from "@silverbulletmd/silverbullet/lib/crypto";
 import { LuaRuntimeError } from "./space_lua/runtime.ts";
 import { resolveASTReference } from "./space_lua.ts";
+import { unregisterServiceWorkers } from "./service_worker/util.ts";

 const frontMatterRegex = /^---\n(([^\n]|\n)*?)---\n/;

@@ -1370,6 +1371,9 @@ export class Client {
         ) {
           location.href = message.actionOrRedirectHeader;
         } else {
+          console.warn("auth-error: Unregistering service workers")
+          await unregisterServiceWorkers()
+          console.warn("auth-error: Reloading")
           location.reload();
         }
         break;
```

**Comment by lutzky** [comment]
The plot thickens. If this happens immediately on boot (that is, the authentication expired before we even loaded the page), then we never even get to registering `handleServiceWorkerMessage`, and nothing responds to the `auth-error` message. Furthermore, the effective crash occurs quite early; `configJSONText` is fetched, 

On a "silverbullet-internal auth error", the return status is 401 with a location header, which is... not to spec? But indeed, that's what `boot.ts` responds to ("Received an (authentication) redirect"). However, for CORS reasons, if *cloudflare* returns the redirect, then it's a cross-origin redirect, which service workers aren't allowed to see. Instead, they get a `Response {type: 'opaqueredirect', redirected: false, status: 0, headers: Headers{}, ...}`. Although `authenticatedFetch` is set up to look at this, `cachedFetch` is not. Also, the nature of `opaqueredirect` is that you don't even know the *destination* of the redirect, which is why we had the call to `unregisterServiceWorkers` to begin with.

I'm wondering if a better approach, instead of unregistering service workers, might be to redirect to a URL which is purposely never cached. (Posting progress updates here in case Zef pops up to say "wait wait I'm fixing it already in another way")

**Comment by zefhemel** [comment]
I'm now (finally) setting up cloudflare for myself. Will have another whack at this.

**Comment by lutzky** [comment]
Amongst the complications here is a redirect loop that seems to go like this:

* `https://MY_SILVERBULLET_DOMAIN_REDACTED/` -> `https://yourusername.cloudflareaccess.com/cdn-cgi/access/login/MY_SILVERBULLET_DOMAIN_REDACTED?kid=LONG_REDACTED_STRING&redirect_url=%2FProjects%2FSilverBullet.md&meta=LONG_REDACTED_STRING`
* ...does some login-y stuff, and then redirects back to:
* `https://MY_SILVERBULLET_DOMAIN_REDACTED/access/authorized?nonce=NONCE_REDACTED&state=STATE_REDACTED`
* ...and then *something* tried to go to the cloudflareaccess.com URL again. Apparently `proxy_router.ts`.

I'm not entirely sure what's going on. I can tell you that, to test it, you can hit "Revoke existing tokens" under "Application Audience (AUD) Tag" in Access Controls under Zero Trust.

**Comment by zefhemel** [comment]
Ok indeed it had to do with opaque redirects. Not super excited about this solution, but should be fixed again...
