### ISSUE TITLE
Web App Not Loading on iOS 17.0 (Fine on later versions)

### ISSUE THREAD

**Issue by getBoolean** [silverbulletmd/silverbullet#1521]
The application will not load on iOS 17.0, see attached image.

I tested with MacOS simulator, I am able to reproduce the issue on iOS 17.0 but not iOS 17.5, so it seems to be fixed on later OS versions.

<img width="977" height="1055" alt="Image" src="https://github.com/user-attachments/assets/ebc52a59-41b3-4f88-b6d6-9b7d44548283" />

Silverbullet Version 2.0.0, installed with Docker. Have not tested older versions.

| Device | OS | Has Issue |
| ------- | ----- | ------- |
| iPhone 13 mini | iOS 17.0 | ✅ |
| iPad Pro 6th gen | iPadOS 17.0 | ✅ |

Also before you ask, I am intentionally on iOS 17.0 for sideloading, so I can't update. I understand something like this is pretty low priority, but I would appreciate if it could be fixed 🙏

**Comment by ursuscamp** [comment]
I'm am getting this problem as well, but it's on iOS 18.6.2, but only when the app is installed as a PWA. When I load it from the browser, it works. When I try to load it from a PWA, it loads exactly as your first screenshot.

**Comment by nitej** [comment]
This is also a problem when installing silverbullet.md 2.0 as a PWA from Safari on MacOS (test on MacOS 15.5 with Safari 18.5). The web console gives the following errors:
```
Viewport argument key "interactive-widget" not recognized and ignored. // silverbullet.md:8
TypeError: undefined is not an object (evaluating 'e.split') // client.js:29:27036
```
Similar errors are thrown in the iOS PWA. This only started showing up for me after upgrading to Silverbullet.md 2.0

**Comment by ursuscamp** [comment]
Yeah, I am seeing an identical error in the developer console. I am quite excited to use this application, but unfortunately this is a bit of a deal breaker until the iOS PWA is working for me.

**Comment by zefhemel** [comment]
This should now be fixed (will be in the edge builds (`:v2` docker tag) in minutes)

**Comment by zefhemel** [comment]
Note: if this is the same issue on iOS and MacOS, please verify — it may not be.

**Comment by getBoolean** [comment]
@zefhemel I am still seeing the issue on iOS after upgrading my instance. I've grabbed the logs using MacOS Simulator and the errors are the same as previously mentioned.

Left - iOS 17.5 works fine. Right - iOS 17.0 and not working after logging in

<img width="1021" height="1398" alt="Image" src="https://github.com/user-attachments/assets/4aa916da-bba0-4ec3-91c4-6df44bc70a37" />

The screenshot includes the version number from the working device.

I am not able to reproduce with a PWA on iOS 17.5, this happens in the browser and PWA on iOS 17.0.
I am not able to to reproduce on MacOS Safari with PWA or in browser

**Comment by ursuscamp** [comment]
I updated to the `v2` tag with docker and it works for me now.

**Comment by zefhemel** [comment]
@getBoolean ah thanks for this, right this is a newer API, we can probably do without. Let me reopen this.

**Comment by zefhemel** [comment]
@getBoolean I'm having trouble installing 17 in my simulator so I have to do this blindly. I just pushed a fix that includes a polyfill for Promise.withResolvers, does it work now?

**Comment by getBoolean** [comment]
It did fix it, thank you so much!
