### ISSUE TITLE
'Slash commands' no longer working 

### ISSUE THREAD

**Issue by thinkbig1979** [silverbulletmd/silverbullet#811]
Upgraded to latest (0.7.6) this morning. Initially had issues due to treeview plug throwing an error, but solved that by following instructions listed in another issue. However, hitting the `/` key no longer does anything, where previously I would get a little menu and I could type `/h2` for example, and it would change the line into an H2 heading. Hitting `/` now simply types a slash, and no menu is invoked. I cannot find any related settings, nor any mention of such an issue in the issues section. 

Running: 
Ubuntu 20.04.6 LTS
Deno 1.41.3
Silverbullet 0.7.6

**Comment by tmichela** [comment]
I had this too. A quick workaround is to reload the page bypassing the cache: `CTRL + SHIFT + R` on firefox

**Comment by zefhemel** [comment]
This sounds like a caching issue indeed. Try to reload the page a few times.

**Comment by thinkbig1979** [comment]
Cleared local storage and "cookies and site data" multiple times, refreshed using ctrl+r and ctrl+shift+r multiple times and even restarted silverbullet. The issue persists unfortunately.

**Comment by zefhemel** [comment]
Can you have a look at your browser's JavaScript console and what errors are there? Have you installed any third party plugs?

**Comment by thinkbig1979** [comment]
I've tested this on Edge and Firefox on windows, and on Firefox on Linux. 
I'm not running any browser extensions on Edge, whereas I am running quite a few on Firefox.
Same thing in all scenarios.

I've deleted all plugs, removed them from the _plugs directory, cleared any settings related to the plugs, and restarted silverbullet.
Cleaned out all local storage related to the webapp in both browsers and the issue still persists.

Zero errors in the console on both browsers.

Interestingly, this issue is not present on the online silverbullet playground. There, the slash key works just fine (from the same machines and browsers).

Really seems to be something wrong with my install by the looks of it.

**Comment by zefhemel** [comment]
And if you point silverbullet at an empty folder, does that help?

**Comment by thinkbig1979** [comment]
Same issue.

**Comment by thinkbig1979** [comment]
What's the best way to neatly and completely uninstall silverbullet? That way I can try a clean install.

**Comment by zefhemel** [comment]
Depending on how you installed Deno, one way would be to remove your ~/.deno folder, which will likely also uninstall Deno. After that follow https://silverbullet.md/Install/Deno again. 

Then run it on an empty folder and perhaps on a new port (-p 3005 for instance) to be sure there's absolutely no caching going on.

**Comment by thinkbig1979** [comment]
Unfortunately, none of the above has had any effect. Puzzling.

**Comment by zefhemel** [comment]
Is this issue still happening, or did it somehow resolve itself?

**Comment by thinkbig1979** [comment]
Still happening, and I just tested running SilverBullet as a docker container, and it still had the same issue on my server.
So it's not a browser thing, it's not a SilverBullet thing or a Deno thing. The only thing the bare metal install and the docker container have in common is the reverse proxy I'm using and the underlying system kernel etc. I will do a test shortly to bypass the reverse proxy (I'll just open the docker mapped port temporarily. Will post here as soon as I have that result.

**Comment by zefhemel** [comment]
Very odd. The only possible explanation I have is some sort of caching. I've just released 0.7.7, perhaps upgrading to that somehow magically fixes things.

**Comment by thinkbig1979** [comment]
Just tried accessing the server directly through the exposed ports from docker to take the reverse proxy out of the equation. I'm afraid the problem still persists. Even tried accessing it from a cleanly installed machine running a browser I've never used. No difference. 😥

**Comment by zefhemel** [comment]
Ok I just installed Brave again on Mac and tested both on https://play.silverbullet.md/ as well as my own installation and slash commands work perfectly. Does this not work for you either?

**Comment by thinkbig1979** [comment]
That's what's so strange. The playground works perfectly for me.
![image](https://github.com/silverbulletmd/silverbullet/assets/18327273/15ffba74-79a2-4999-947d-fb7cf58f960d)

But on the same browser or any other browser, if I go to my self-hosted version, the issue remains.
![image](https://github.com/silverbulletmd/silverbullet/assets/18327273/9710463e-1300-4e2b-b6e6-fb5426b539db)

**Comment by zefhemel** [comment]
And you have a valid SSL certificate, you load SB through https://sbt.qtpl.net (that's referenced in your comment) and you don't have weird authentication proxies or whatever on top?

**Comment by thinkbig1979** [comment]
Just spun up a new container, and fresh installed chromium.  Same issue on my end.
![image](https://github.com/silverbulletmd/silverbullet/assets/18327273/362e6a0f-ef74-4bf5-b57d-8e4b16f11899)

**Comment by zefhemel** [comment]
The default install of SilverBullet may not come with any slash commands I think, did you install the core library? https://silverbullet.md/Library/Core

**Comment by thinkbig1979** [comment]
If it's included in the default docker container at `image: zefhemel/silverbullet`, then yes, otherwise, no.

**Comment by thinkbig1979** [comment]
Yes! That did the trick! Thanks Zef!

**Comment by zefhemel** [comment]
I'm closing this, since I think we found the root cause. I'll think if I can find a better way to distribute a default library without having to do an explicit import.
